const GARDENS = [
 {"name":"纽约明轩","en":"The Astor Chinese Garden Court","place":"美国 · 纽约 · 大都会艺术博物馆","year":"1981年开放","shortyear":"1981","type":"苏州园林式庭院","intro":"明轩是一座设置在博物馆内的中式庭院，以苏州网师园的一处庭院为原型。它把苏州园林的庭院空间带进纽约，让观众在参观中国艺术品时，也能感受传统园林的环境。","features":"以太湖石、砖瓦铺地、木柱、梁架和格扇等构成庭院。与完整室外园林相比，明轩规模较小，但建筑、山石与庭院关系十分集中。","background":"大都会艺术博物馆的官方资料确认，苏州工匠参与明轩营造。","sources":[["大都会艺术博物馆 · 明轩藏品及实景","https://www.metmuseum.org/art/collection/search/78870"],["大都会艺术博物馆 · 苏州工匠营造记录","https://www.metmuseum.org/it/perspectives/astor-court-asmr"],["大都会艺术博物馆 · 开放年份与庭院原型","https://www.metmuseum.org/it/perspectives/water-features-at-the-met-fifth-avenue"]]},
 {"name":"温哥华中山公园古典园林","en":"Dr. Sun Yat-Sen Classical Chinese Garden","place":"加拿大 · 温哥华 · 唐人街","year":"1985至1986年建设，1986年开放","shortyear":"1986","type":"苏州工匠参与的古典园林","intro":"这是一座位于温哥华市区的明代风格中国古典园林。园方介绍，它由当地社区、加拿大政府与中方合作建设，兼具游览和中国文化展示用途。","features":"以园林住宅的尺度组织建筑与庭院，将亭廊、水池、山石和植物组合在围墙之内。这里所列的是古典园林部分，不与相邻的公共公园混为一谈。","background":"温哥华市议会档案明确记载，52名苏州工匠参与1985至1986年的建设。","sources":[["温哥华市议会 · 建设及苏州工匠记录","https://council.vancouver.ca/991021/Pe1.htm"],["园方官网 · 项目介绍及实景","https://vancouverchinesegarden.com/"]]},
 {"name":"波特兰兰苏园","en":"Lan Su Chinese Garden","place":"美国 · 俄勒冈州 · 波特兰","year":"2000年9月14日开放","shortyear":"2000","type":"苏州友城合作园林","intro":"兰苏园源于波特兰与苏州的友好城市合作。“兰苏”的名称结合了两座城市的名字，是海外苏州园林中有代表性的一处。","features":"园中可见太湖石、传统建筑、庭院和石子拼铺路面。建筑与游路相互穿插，把山石、水景和植物安排在紧凑的城市空间中。","background":"园方25周年资料记载，60余名中国工匠先在苏州制作主要结构，再将构件运到波特兰重新组装。","sources":[["兰苏园 · 25周年历史及建设介绍","https://lansugarden.org/yuan-together-25-years-of-lan-su/"],["兰苏园 · 官方导览","https://lansugarden.org/content/CI_assets/SocialDistanceDigitalGuide.pdf"]]},
 {"name":"圣马力诺流芳园","en":"Liu Fang Yuan · The Huntington","place":"美国 · 加利福尼亚州 · 圣马力诺（洛杉矶地区）","year":"2008年首次开放，2020年扩建开放","shortyear":"2008／2020","type":"苏州设计与工匠参与的园林","intro":"流芳园位于亨廷顿图书馆、艺术博物馆及植物园内。园方2020年资料记载，扩建后面积达到15英亩，约6.1公顷，是海外规模较大的中国古典风格园林之一。","features":"以湖面为中心，布置亭、桥、廊、庭院、山石和展示空间。建筑题名、书法与园景相结合，形成具有江南文人园林特点的游览环境。","background":"由苏州设计机构、苏州工匠与美国建筑、工程及施工团队合作完成；当地团队同时处理抗震和无障碍等要求。","sources":[["亨廷顿官方 · 2020年扩建与中美团队介绍","https://www.huntington.org/news/expanded-chinese-garden-opens/"],["亨廷顿官方 · 园林实景","https://www.huntington.org/filming-and-photography/commercial-filming-and-photography/commercial-filming-and-photography-0-5"]]},
 {"name":"纽约寄兴园","en":"New York Chinese Scholar’s Garden","place":"美国 · 纽约 · 史泰登岛 Snug Harbor","year":"1999年开放","shortyear":"1999","type":"苏州制作构件的中式园林","intro":"寄兴园位于纽约史泰登岛的Snug Harbor文化中心及植物园内，以明代园林为灵感，是当地展示中国园林艺术的场所。","features":"园中有亭、竹径、瀑布、水池、曲折的桥与游路，以及形态各异的赏石。木构件采用传统榫卯连接，园路铺装也体现了细致的手工制作。","background":"园方记载，屋瓦、木梁及铺地等构件在苏州制作。40名艺术家和工匠组成的团队，用一年制作构件，再在当地进行约六个月的组装。","sources":[["Snug Harbor官方 · 寄兴园介绍及实景","https://snug-harbor.org/things-to-do/outdoor-exploration/chinese-scholars-garden/"]]},
 {"name":"马耳他静园","en":"Garden of Serenity","place":"马耳他 · 桑塔露琪亚","year":"1997年3月竣工","shortyear":"1997","type":"苏州古典园林","intro":"静园是中国政府在马耳他援建的苏州古典园林项目。中国驻马耳他使馆资料记载，项目于1997年3月竣工，占地约8,000平方米。","features":"园中布置人工湖、瀑布、曲折小径和亭子，木构建筑临水展开。这座园林将中国传统园林景观带入地中海地区的城市环境。","background":"马耳他公园网站记载，园林由中国苏州园林设计机构的专家设计。","sources":[["中国驻马耳他使馆 · 竣工年代与项目背景","https://mt.china-embassy.gov.cn/chn/sgdt/202206/t20220616_10704003.htm"],["马耳他公园网站 · 静园介绍及实景","https://parksinmalta.mt/park/serenity-garden/"]]},
 {"name":"新加坡裕华园盆景园","en":"Bonsai Garden · Chinese Garden","place":"新加坡 · 裕廊湖区 · 裕华园内","year":"盆景园1992年建成","shortyear":"1992","type":"苏州工匠参与的盆景园","intro":"这里介绍的是裕华园内的盆景园，而不是把整个裕华园都归为苏式园林。新加坡国家文物局资料记载，盆景园建于1992年，有55名苏州工匠参与建设。","features":"以厅堂、庭院、盆景陈设和传统园林空间相结合。新加坡国家公园局导览也明确以苏州园林作为这处盆景园的设计参照。","background":"属于有明确苏州工匠参与记录的海外项目。1992年指盆景园的建成年代，不是裕华园整体的开放年份。","sources":[["新加坡国家文物局 · 裕华园建设历史","https://www.roots.gov.sg/resources-landing/online-exhibitions/chinese-garden"],["新加坡国家公园局 · 中国园官方导览","https://juronglakegardens.nparks.gov.sg/files/Guided%20Tours/DIY_CHINESE_GARDEN_GUIDE.pdf"]]},
 {"name":"蒙特利尔植物园中国园","en":"Chinese Garden · Montréal Botanical Garden","place":"加拿大 · 蒙特利尔 · 植物园","year":"1991年6月开放","shortyear":"1991","type":"上海团队参与的中国园林","intro":"中国园是蒙特利尔植物园的重要园区，建成于1990至1991年间。园方介绍，项目源于蒙特利尔植物园与上海园林部门之间的长期合作。","features":"园方以植物、水、石和建筑四项要素解释园林的构成。园中把建筑与山水布置结合起来，并展示中国植物及园林文化。","background":"园林设计由上海园林设计专家乐卫忠主持，50名中国工匠参与构件组装。官方资料确认的是上海方面合作，不将其列作已核实的香山帮项目。","sources":[["蒙特利尔植物园 · 设计与营造介绍","https://espacepourlavie.ca/en/locations/chinese-garden"],["蒙特利尔植物园 · 开放年代及园景","https://m.espacepourlavie.ca/node/3850?lang=en"]]},
 {"name":"德国波鸿潜园","en":"Qian Yuan · Ruhr University Bochum","place":"德国 · 波鸿 · 鲁尔大学植物园","year":"1990年建成","shortyear":"1990","type":"中国南方文人园林","intro":"潜园是上海同济大学赠予德国波鸿鲁尔大学的友好合作礼物，建于鲁尔大学成立25周年之际，占地约1,000平方米。","features":"大学官方将其介绍为中国南方风格的古典文人园林。园内以水面、亭屋、山石和植物形成安静的庭园空间，园名与陶潜及《桃花源记》有关。","background":"已确认的合作关系是上海同济大学与波鸿鲁尔大学；不因具有江南园林风貌，就直接认定为苏州工匠营造。","sources":[["波鸿鲁尔大学 · 潜园介绍及实景","https://www.boga.ruhr-uni-bochum.de/bg/garten/chinesischergarten/index.html.de"],["波鸿鲁尔大学 · 植物园英文介绍","https://www.boga.ruhr-uni-bochum.de/garten/"]]},
 {"name":"苏黎世中国园","en":"Chinagarten Zürich","place":"瑞士 · 苏黎世 · 苏黎世湖畔","year":"1994年开放","shortyear":"1994","type":"昆明赠建的中式园林","intro":"苏黎世中国园是昆明赠予友好城市苏黎世的礼物，用于感谢苏黎世对昆明供水和排水建设的支持。项目于1994年开放。","features":"以“岁寒三友”为主题，园内有池塘、小岛、亭子、桥、山石和水榭式建筑。红色围墙、屋顶和临水建筑是其醒目的外观特征。","background":"苏黎世市政府资料确认其昆明背景。这是一处中式园林，但不应列作已有证据证明的苏州或香山帮营造项目。","sources":[["苏黎世市政府 · 中国园介绍及实景","https://www.stadt-zuerich.ch/chinagarten"]]},
 {"name":"悉尼谊园","en":"Chinese Garden of Friendship","place":"澳大利亚 · 悉尼 · 达令港","year":"1988年1月17日开放","shortyear":"1988","type":"广东背景的中式园林","intro":"谊园建于悉尼达令港地区，是澳大利亚新南威尔士州与中国广东省合作的成果，也纪念悉尼与广州之间的友好关系。","features":"以中国传统私家园林为参照，将水景、建筑和植物组合在城市中心。园中龙壁由广东赠送，两条龙分别象征广东和新南威尔士州。","background":"园方介绍，项目由中国景观设计师设计，澳大利亚工匠和专业人员参与建造。其地域文化背景是广东，不归入苏式园林。","sources":[["新南威尔士州政府 · 开放年代与合作背景","https://www.nsw.gov.au/visiting-and-exploring-nsw/locations-and-attractions/chinese-garden-of-friendship"],["达令港官方 · 谊园历史及实景","https://www.darlingharbour.com/precincts/chinese-garden/history-of-the-garden"]]},
 {"name":"新西兰但尼丁兰园","en":"Lan Yuan · Dunedin Chinese Garden","place":"新西兰 · 但尼丁","year":"2008年6月对公众开放，同年9月举行正式开园仪式","shortyear":"2008","type":"江南传统园林","intro":"兰园由但尼丁市与上海方面支持建设，以纪念当地华人的历史与贡献。它在2008年向公众开放，是海外江南风格园林的代表作品之一。","features":"园方明确说明，设计以江南传统园林为基础，适合在城市中较小的场地内组织园林空间。园中设有茶室等建筑，供人游览和停留。","background":"由上海交通大学、同济大学及上海博物馆相关专家参与设计；先在上海按同样场地尺寸制作和试装，再拆运至新西兰，由上海工匠重建。","sources":[["但尼丁兰园官方 · 设计建设及开放历史","https://www.dunedinchinesegarden.com/history/about-the-garden"]]}
]
;